server:
  port: 80
spring:
  application:
    name: cncdy-crowd-zuul
  redis:
    host: localhost
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"
  sensitive-headers: "*" # 在 Zuul 向其他微服务重定向时保持原本头信息（请求头、响应头）
  routes:
    crowd-portal:
      service-id: cncdy-crowd-auth
      path: /** # 这里一定要使用两个“*”号，不然“/”路径后面的多层路径将无法访问
    crowd-project:
      service-id: cncdy-crowd-project
      path: /project/**
    crowd-order:
      service-id: cncdy-crowd-order
      path: /order/**
    crowd-pay:
      service-id: cncdy-crowd-pay
      path: /pay/**
ribbon:
  ReadTimeout: 61000
  ConnectTimeout: 61000