server:
  port: 3000
spring:
  application:
    name: cncdy-crowd-redis
  redis:
    host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ribbon:
  eureka:
    enabled: true